name: Tests

on:
  pull_request:
  push:
    branches:
      - master
      - '[0-9]+.x'
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [5.4, 5.5, 5.6, '7.0', 7.1, 7.2, 7.3, 7.4, '8.0', 8.1, 8.2, 8.3, 8.4]
        stability: [lowest, highest]

    name: PHP ${{ matrix.php }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@2.31.1
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, xdebug
          coverage: xdebug

      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - if: matrix.php < '7.3'
        name: Remove code lint dependencies
        run: composer remove zing/coding-standard phpstan/phpstan phpstan/phpstan-mockery --no-update --dev

      - if: matrix.php >= '7.0'
        name: Bump phpunit greater than 6.5
        run: composer require phpunit/phpunit:'^6.5 || ^7.5 || ^8.5 || ^9.3.3 || ^10.0 || ^11.0' --no-update --dev

      - if: matrix.php >= '7.2'
        name: Bump yii2 framework greater than 2.0.13
        run: composer require yiisoft/yii2:~2.0.13 --no-update

      - if: matrix.php >= '7.3'
        name: Bump phpunit greater than 9.3.3
        run: composer require phpunit/phpunit:'^9.3.3 || ^10.0 || ^11.0' --no-update --dev

      - name: Install dependencies
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: ${{ matrix.stability }}

      - name: Execute tests
        run: composer run-script test:phpunit -- --coverage-clover coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        continue-on-error: true
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage to Code Climate
        uses: paambaati/codeclimate-action@v9.0.0
        continue-on-error: true
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: ls
          coverageLocations: ${{github.workspace}}/coverage.xml:clover
